services:

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - student-network

  student-app:
    image: saqib321/student-app:latest
    pull_policy: always
    container_name: student-app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: postgres-db
      DB_USER: admin
      DB_PASSWORD: secret
      DB_NAME: mydb
    depends_on:
      - postgres-db
    networks:
      - student-network

networks:
  student-network:
    driver: bridge

volumes:
  postgres-data:
